#!/usr/bin/env bash
set -euo pipefail

# Run the WSI integration contract against the exact backend/Core/frontend/tile
# tuple used by the validation manifest.  This script is intentionally kept in
# the validation PR: it is a release gate and is never part of ordinary portal
# publication.
#
# WSI uses the resource-data model: the fixture studies under
# src/e2e/js/test/WsiHierarchyController/wsi_loader_*fixture are generated by
# the pinned Core convertWsiToResources.py (scripts/wsi_resource_fixtures.py)
# and import as resource_definition + resource_data rows (RESOURCE_ID
# WSI_SAMPLE/WSI_PATIENT, TYPE WHOLE_SLIDE_IMAGE, METADATA with the private
# wsi_serving object).  The native wsi_* tables still exist but must stay empty.

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${BACKEND_DIR:?BACKEND_DIR must point at the pinned resource-data backend checkout}"
BACKEND_REF="${BACKEND_REF:?BACKEND_REF is required}"
TEST_STACK_DIR="${TEST_STACK_DIR:?TEST_STACK_DIR must point at the pinned test-stack checkout}"
FRONTEND_DIR="${FRONTEND_DIR:?FRONTEND_DIR must point at the pinned frontend integration checkout}"
FRONTEND_REF="${FRONTEND_REF:?FRONTEND_REF must match the selected frontend variant}"
TILE_DIR="${TILE_DIR:?TILE_DIR must point at the pinned tile-server checkout}"
CORE_REPOSITORY="${CORE_REPOSITORY:?CORE_REPOSITORY is required}"
CORE_REF="${CORE_REF:?CORE_REF is required}"
COMPOSE_REPOSITORY="${COMPOSE_REPOSITORY:?COMPOSE_REPOSITORY is required}"
COMPOSE_REF="${COMPOSE_REF:?COMPOSE_REF is required}"
IMAGE="${WSI_PORTAL_IMAGE:-cbioportal-wsi-validation:local}"
PROJECT="${COMPOSE_PROJECT_NAME:-wsi-validation}"
AUTH_SECRET="${WSI_AUTH_SECRET:-local-development-wsi-secret-change-me-32chars}"
AUTH_AUDIENCE="${WSI_AUTH_AUDIENCE:-cbioportal-wsi}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
WSI_VARIANT="${WSI_VARIANT:-integration}"

test -x "$TEST_STACK_DIR/utils/check-connection.sh"
test "$(git -C "$BACKEND_DIR" rev-parse HEAD)" = "$BACKEND_REF"
test "$(git -C "$FRONTEND_DIR" rev-parse HEAD)" = "$FRONTEND_REF"

COMPOSE_DIR="${RUNNER_TEMP:-/tmp}/wsi-validation-compose"
COMPOSE_OVERRIDE="${ROOT_DIR}/src/e2e/js/test/WsiHierarchyController/wsi_ci_compose_override.yml"
COMPOSE_AUTH_OVERRIDE="${ROOT_DIR}/src/e2e/js/test/WsiHierarchyController/wsi_ci_auth_compose_override.yml"
FRONTEND_LOG="${RUNNER_TEMP:-/tmp}/wsi-frontend.log"
COMPOSE_LOG="${RUNNER_TEMP:-/tmp}/wsi-compose.log"
TILE_LOG="${RUNNER_TEMP:-/tmp}/wsi-tile.log"
FULL_STACK_LOG="${RUNNER_TEMP:-/tmp}/wsi-full-stack.log"
ACTIVE_COMPOSE_FILES=()
STACK_STARTED=false

# Keep the command-level trace alongside the service logs.  The compose log
# contains container output, but importer/API/browser failures happen in this
# shell and otherwise leave only an exit code in the Actions UI.
exec > >(tee -a "$FULL_STACK_LOG") 2>&1

log() {
  printf '[wsi-full-stack] %s\n' "$*"
}

wait_http() {
  local url="$1"
  local retries="${2:-180}"
  local insecure="${3:-}"
  for _ in $(seq 1 "$retries"); do
    if curl --fail --silent --show-error ${insecure:+--insecure} "$url" >/dev/null; then
      return 0
    fi
    sleep 2
  done
  return 1
}

compose() {
  docker compose -p "$PROJECT" -f "$COMPOSE_DIR/docker-compose.yml" "$@"
}

stop_frontend() {
  if [[ -n "${FRONTEND_PID:-}" ]]; then
    # rspack is started through pnpm, which leaves descendants behind when
    # only the shell wrapper is terminated.  Start the server in its own
    # session and terminate the entire process group so the next auth mode
    # cannot reuse the previous mode's frontend.
    kill -- "-${FRONTEND_PID}" 2>/dev/null || true
    kill "$FRONTEND_PID" 2>/dev/null || true
    wait "$FRONTEND_PID" 2>/dev/null || true
    unset FRONTEND_PID
  fi
}

stop_tile() {
  docker rm -f wsi-validation-tile wsi-validation-redis >/dev/null 2>&1 || true
}

stop_compose() {
  stop_frontend
  if [[ ${#ACTIVE_COMPOSE_FILES[@]} -gt 0 ]]; then
    compose "${ACTIVE_COMPOSE_FILES[@]}" down --volumes --remove-orphans >/dev/null 2>&1 || true
  else
    compose down --volumes --remove-orphans >/dev/null 2>&1 || true
  fi
  stop_tile
}

cleanup() {
  set +e
  if [[ "$STACK_STARTED" == true ]]; then
    {
      echo '--- compose ps ---'
      compose ps
      echo '--- cbioportal logs ---'
      compose logs --no-color cbioportal
      echo '--- migration logs ---'
      compose logs --no-color cbioportal-migration
    } >>"$COMPOSE_LOG" 2>&1
  fi
  stop_compose
}
trap cleanup EXIT

build_portal_image() {
  log "building portal image ${IMAGE} from backend $(git -C "$BACKEND_DIR" rev-parse HEAD) with Core ${CORE_REF}"
  docker build \
    --build-arg CORE_REPOSITORY="$CORE_REPOSITORY" \
    --build-arg CORE_REF="$CORE_REF" \
    --tag "$IMAGE" \
    --file "$BACKEND_DIR/docker/web-and-data/Dockerfile" \
    "$BACKEND_DIR"
  docker image inspect "$IMAGE" --format 'portal image={{.Id}} created={{.Created}}' | tee -a "$FULL_STACK_LOG"
}

build_tile_image() {
  log "building pinned tile image"
  docker build --tag wsi-validation-tile-image:local "$TILE_DIR"
}

start_tile() {
  local port="$1"
  stop_tile
  docker network create wsi-validation-tile-net >/dev/null 2>&1 || true
  docker run -d \
    --name wsi-validation-redis \
    --network wsi-validation-tile-net \
    redis:7.4.5-alpine redis-server --save '' --appendonly no >/dev/null
  docker run -d \
    --name wsi-validation-tile \
    --network wsi-validation-tile-net \
    --publish "${port}:8080" \
    --link wsi-validation-redis:redis \
    --env WSI_AUTH_SECRET="$AUTH_SECRET" \
    --env WSI_AUTH_AUDIENCE="$AUTH_AUDIENCE" \
    --env WSI_ALLOWED_SOURCE_SCHEMES=file \
    --env WSI_ALLOWED_SOURCE_PREFIXES=file:///app/testdata/ \
    --env WSI_ALLOWED_THUMBNAIL_PREFIXES=file:///app/testdata/ \
    --env REDIS_URL=redis://redis:6379 \
    --volume "$TILE_DIR/tests/testdata:/app/testdata:ro" \
    wsi-validation-tile-image:local \
    >"$TILE_LOG" 2>&1
  wait_http "http://127.0.0.1:${port}/ready" 120
}

prepare_compose() {
  log "preparing pinned compose stack"
  rm -rf "$COMPOSE_DIR"
  git clone --filter=blob:none --no-checkout \
    "https://github.com/${COMPOSE_REPOSITORY}.git" "$COMPOSE_DIR"
  git -C "$COMPOSE_DIR" fetch --depth 1 origin "$COMPOSE_REF"
  git -C "$COMPOSE_DIR" checkout --detach "$COMPOSE_REF"
  cat >"$COMPOSE_DIR/.env" <<EOF
DOCKER_IMAGE_CBIOPORTAL=${IMAGE}
DOCKER_IMAGE_SESSION_SERVICE=cbioportal/session-service:0.6.4
DOCKER_IMAGE_MYSQL=mysql:8.1.0
DOCKER_IMAGE_CLICKHOUSE=clickhouse/clickhouse-server:24.10
CLICKHOUSE_DB=cbioportal
CLICKHOUSE_USER=cbio_user
CLICKHOUSE_PASSWORD=somepassword
CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
CLICKHOUSE_HOST=cbioportal-database
CLICKHOUSE_HTTP_PORT=8123
CLICKHOUSE_NATIVE_PORT=9000
# The ClickHouse JDBC driver does not inherit the server profile for this
# setting. Pass it explicitly so lifecycle DELETE uses projection-safe mode.
CLICKHOUSE_URL=jdbc:ch://cbioportal-database:8123/cbioportal?custom_settings=lightweight_mutation_projection_mode%3Ddrop
CLICKHOUSE_OPTIMIZE_BACKOFF_SECS=0
CLICKHOUSE_SETTINGS_PATH=./data/clickhouse_user_settings.xml
CBIOPORTAL_SERVER_PORT=8080
SHOW_DEBUG_INFO=true
APPLICATION_PROPERTIES_PATH=./config/application.properties
SESSION_SERVICE_SERVER_PORT=5001
SESSION_SERVICE_JAVA_OPTS=-Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
MONGO_INITDB_DATABASE=session_service
CBIOPORTAL_SOURCE_DIR=${ROOT_DIR}
CBIOPORTAL_BACKEND_SOURCE_DIR=${BACKEND_DIR}
WSI_AUTH_SECRET=${AUTH_SECRET}
WSI_AUTH_AUDIENCE=${AUTH_AUDIENCE}
WSI_ALLOWED_SOURCE_PREFIXES=file:///app/testdata/
WSI_ALLOWED_THUMBNAIL_PREFIXES=file:///app/testdata/
EOF
  mkdir -p "$COMPOSE_DIR/study"
  # The pinned compose helper resolves its environment file relative to the
  # directory containing each script. Invoke both helpers from their own
  # directories so the generated application properties and fixture SQL are
  # complete before any service starts.
  (cd "$COMPOSE_DIR/config" && ./init.sh)
  (cd "$COMPOSE_DIR/data" && ./init.sh)
}

start_compose() {
  local mode="$1"
  local tile_port="$2"
  local portal_authenticate="$3"
  local local_bypass="$4"
  local compose_files=(-f "$COMPOSE_DIR/docker-compose.yml" -f "$COMPOSE_OVERRIDE")

  export WSI_AUTHENTICATE="$portal_authenticate"
  export WSI_LOCAL_AUTH_BYPASS="$local_bypass"
  # The browser must receive the deployed same-origin tile URL.  The
  # validation frontend proxies that path to the pinned tile service below;
  # API tests continue to use WSI_TILE_SERVER_PORT directly.  Keeping these
  # URLs separate catches an accidental cross-origin tile configuration while
  # preserving the backend/tile service contract.
  export WSI_TILE_SERVER_URL="https://localhost:${FRONTEND_PORT}/wsi"
  export WSI_BASIC_USERNAME=wsi-ci-user
  export WSI_BASIC_PASSWORD='$2b$10$7MoXjWmDD/mrvq7hF9D0RuFewhTzl8KYATtySCSZX7tMV.614kO3.'
  export WSI_BASIC_AUTHORITIES=PUBLIC_STUDIES
  export WSI_REQUIRE_AUTHENTICATED_SETUP=false
  if [[ "$mode" == authenticated ]]; then
    compose_files+=(-f "$COMPOSE_DIR/dev/keycloak/keycloak.yml" -f "$COMPOSE_AUTH_OVERRIDE")
    export WSI_REQUIRE_AUTHENTICATED_SETUP=true
    compose -f "$COMPOSE_DIR/dev/keycloak/keycloak.yml" up keycloak -d >"$COMPOSE_LOG" 2>&1
    wait_http http://127.0.0.1:8081/auth/realms/cbio/protocol/saml/descriptor 180
    curl --fail --silent http://127.0.0.1:8081/auth/realms/cbio/protocol/saml/descriptor \
      >"$COMPOSE_DIR/dev/keycloak/idp-metadata.xml"
  fi

  log "starting ${mode} portal stack"
  ACTIVE_COMPOSE_FILES=("${compose_files[@]}")
  STACK_STARTED=true
  local compose_attempt
  for compose_attempt in 1 2 3; do
    if compose "${compose_files[@]}" up -d >>"$COMPOSE_LOG" 2>&1; then
      break
    fi
    if [[ "$compose_attempt" == 3 ]]; then
      return 1
    fi
    log "compose startup attempt ${compose_attempt} failed; waiting for ClickHouse and retrying"
    sleep 10
  done
  wait_http http://127.0.0.1:8080/api/health 180
  log "checking ClickHouse projection-delete setting"
  docker inspect cbioportal-database-container \
    --format '{{range .Mounts}}{{println .Source " -> " .Destination}}{{end}}' \
    | tee -a "$COMPOSE_LOG"
  docker exec cbioportal-database-container \
    sh -lc 'cat /etc/clickhouse-server/users.d/wsi-ci.xml' \
    | tee -a "$COMPOSE_LOG"
  docker exec cbioportal-database-container sh -lc '
    clickhouse-client --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" \
      --database "$CLICKHOUSE_DB" \
      --query "SELECT name, value, changed FROM system.settings WHERE name = '\''lightweight_mutation_projection_mode'\''"
  ' | tee -a "$COMPOSE_LOG"
}

ch_query() {
  # Run one ClickHouse query inside the database container and print TSV.
  docker exec -e WSI_QUERY="$1" cbioportal-database-container sh -lc '
    clickhouse-client --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" \
      --database "$CLICKHOUSE_DB" --query "$WSI_QUERY"
  '
}

import_study() {
  local study_dir="$1"
  docker exec -e WSI_STUDY_DIR="$study_dir" cbioportal-container sh -lc '
    export PORTAL_HOME=/cbioportal-webapp
    export CLICKHOUSE_HOST="${CLICKHOUSE_HOST:-cbioportal-database}"
    export CLICKHOUSE_NATIVE_PORT="${CLICKHOUSE_NATIVE_PORT:-9000}"
    export CLICKHOUSE_DB="${CLICKHOUSE_DB:-cbioportal}"
    export JAVA_OPTS="-Dspring.datasource.url=$CLICKHOUSE_URL -Dspring.datasource.username=$CLICKHOUSE_USER -Dspring.datasource.password=$CLICKHOUSE_PASSWORD -Dspring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver -Dspring.datasource.clickhouse.url=$CLICKHOUSE_URL -Dspring.datasource.clickhouse.username=$CLICKHOUSE_USER -Dspring.datasource.clickhouse.password=$CLICKHOUSE_PASSWORD -Dspring.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver"
    python3 /core/scripts/importer/metaImport.py -s "$WSI_STUDY_DIR" -n -o --derived-table-sql /tmp/wsi-clickhouse.sql
  '
}

# Count WSI resource rows of one study, optionally narrowed by an extra
# predicate on resource_data (aliased r).
wsi_resource_count() {
  local study="$1"
  local predicate="${2:-1}"
  ch_query "SELECT count() FROM resource_data AS r INNER JOIN cancer_study AS s ON s.cancer_study_id = r.CANCER_STUDY_ID WHERE s.cancer_study_identifier = '${study}' AND r.RESOURCE_ID IN ('WSI_SAMPLE', 'WSI_PATIENT') AND r.TYPE = 'WHOLE_SLIDE_IMAGE' AND (${predicate})"
}

expect_count() {
  local label="$1"
  local expected="$2"
  local actual="$3"
  if [[ "$actual" != "$expected" ]]; then
    echo "WSI row-count check failed: ${label}: expected ${expected}, got ${actual:-<empty>}" >&2
    return 1
  fi
  log "ok ${label} = ${actual}"
}

check_imported_wsi_resources() {
  local study="$1"
  local sample_rows="$2"
  local patient_rows="$3"
  local servable_rows="$4"
  local patient_id="$5"
  local undated_viewable="$6"
  local patient_slides="$7"
  local study_db_id
  study_db_id="$(ch_query "SELECT cancer_study_id FROM cancer_study WHERE cancer_study_identifier = '${study}' FORMAT TSVRaw")"
  test -n "$study_db_id"
  expect_count "${study} WSI resource definitions" 2 \
    "$(ch_query "SELECT count() FROM resource_definition WHERE cancer_study_id = ${study_db_id} AND resource_id IN ('WSI_SAMPLE', 'WSI_PATIENT')")"
  expect_count "${study} WSI_SAMPLE rows (sample-matched)" "$sample_rows" \
    "$(wsi_resource_count "$study" "r.RESOURCE_ID = 'WSI_SAMPLE' AND r.ENTITY_TYPE = 'SAMPLE' AND r.SAMPLE_ID IS NOT NULL")"
  expect_count "${study} WSI_PATIENT rows (unmatched)" "$patient_rows" \
    "$(wsi_resource_count "$study" "r.RESOURCE_ID = 'WSI_PATIENT' AND r.ENTITY_TYPE = 'PATIENT' AND r.SAMPLE_ID IS NULL")"
  expect_count "${study} rows carrying a wsi_serving source" "$servable_rows" \
    "$(wsi_resource_count "$study" "JSONExtractString(ifNull(r.METADATA, '{}'), 'wsi_serving', 'source_url') != ''")"
  expect_count "${study} rows without a wsi_serving object" 0 \
    "$(wsi_resource_count "$study" "NOT JSONHas(ifNull(r.METADATA, '{}'), 'wsi_serving')")"
  # The package shows the Pathology Slides tab only when WSI_PATIENT_SLIDE_COUNT
  # > 0 (or it is the active tab), so the browser contracts rely on the
  # imported patient count.
  expect_count "${study} ${patient_id} WSI_PATIENT_SLIDE_COUNT" "$patient_slides" \
    "$(ch_query "SELECT any(cp.attr_value) FROM clinical_patient AS cp INNER JOIN patient AS p ON p.internal_id = cp.internal_id WHERE p.cancer_study_id = ${study_db_id} AND p.stable_id = '${patient_id}' AND cp.attr_id = 'WSI_PATIENT_SLIDE_COUNT'")"
  # The converter's patient attribute counting viewable slides without a
  # procedure day (the frontend's undated notice reads it).
  expect_count "${study} ${patient_id} WSI_PATIENT_UNDATED_SLIDE_COUNT" "$undated_viewable" \
    "$(ch_query "SELECT any(cp.attr_value) FROM clinical_patient AS cp INNER JOIN patient AS p ON p.internal_id = cp.internal_id WHERE p.cancer_study_id = ${study_db_id} AND p.stable_id = '${patient_id}' AND cp.attr_id = 'WSI_PATIENT_UNDATED_SLIDE_COUNT'")"
  # Studies no longer load a PATHOLOGY SLIDES clinical-event file.
  expect_count "${study} PATHOLOGY SLIDES clinical events" 0 \
    "$(ch_query "SELECT count() FROM clinical_event AS e INNER JOIN patient AS p ON p.internal_id = e.patient_id WHERE p.cancer_study_id = ${study_db_id} AND e.event_type = 'PATHOLOGY SLIDES'")"
  # The native WSI tables are no longer written or read.
  local wsi_table
  for wsi_table in wsi_patient wsi_part wsi_block wsi_slide wsi_slide_placement wsi_slide_timing; do
    expect_count "${study} native ${wsi_table} rows" 0 \
      "$(ch_query "SELECT count() FROM ${wsi_table} WHERE cancer_study_id = ${study_db_id}")"
  done
  WSI_STUDY_DB_ID="$study_db_id"
}

import_fixture_and_check_lifecycle() {
  log "importing converted WSI resource fixtures"
  for _ in $(seq 1 150); do
    if ch_query "SELECT 1" >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
  import_study /tmp/wsi-loader-fixture
  import_study /tmp/wsi-loader-control-fixture
  check_imported_wsi_resources msk_spectrum_tme_2022 2 2 3 P-0055908 1 4
  local study_db_id="$WSI_STUDY_DB_ID"
  expect_count "WSI-CI-NO-SLIDES-PATIENT WSI_PATIENT_SLIDE_COUNT rows (tab hidden)" 0 \
    "$(ch_query "SELECT count() FROM clinical_patient AS cp INNER JOIN patient AS p ON p.internal_id = cp.internal_id WHERE p.cancer_study_id = ${study_db_id} AND p.stable_id = 'WSI-CI-NO-SLIDES-PATIENT' AND cp.attr_id = 'WSI_PATIENT_SLIDE_COUNT'")"
  check_imported_wsi_resources wsi_ci_study_b 2 1 2 WSI-CI-B-PATIENT 0 3

  log "checking deletion and clean reimport"
  docker exec cbioportal-container sh -lc '
    export PORTAL_HOME=/cbioportal-webapp
    export CLICKHOUSE_HOST="${CLICKHOUSE_HOST:-cbioportal-database}"
    export CLICKHOUSE_NATIVE_PORT="${CLICKHOUSE_NATIVE_PORT:-9000}"
    export CLICKHOUSE_DB="${CLICKHOUSE_DB:-cbioportal}"
    export JAVA_OPTS="-Dspring.datasource.url=$CLICKHOUSE_URL -Dspring.datasource.username=$CLICKHOUSE_USER -Dspring.datasource.password=$CLICKHOUSE_PASSWORD -Dspring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver -Dspring.datasource.clickhouse.url=$CLICKHOUSE_URL -Dspring.datasource.clickhouse.username=$CLICKHOUSE_USER -Dspring.datasource.clickhouse.password=$CLICKHOUSE_PASSWORD -Dspring.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver"
    cbioportalImporter.py -c remove-study -id msk_spectrum_tme_2022
  '
  expect_count "removed study resource_data rows" 0 \
    "$(ch_query "SELECT count() FROM resource_data WHERE CANCER_STUDY_ID = ${study_db_id}")"
  expect_count "removed study resource_definition rows" 0 \
    "$(ch_query "SELECT count() FROM resource_definition WHERE cancer_study_id = ${study_db_id}")"
  import_study /tmp/wsi-loader-fixture
  check_imported_wsi_resources msk_spectrum_tme_2022 2 2 3 P-0055908 1 4

  # The portal's default authorization cache is populated at application
  # startup.  The importer runs after compose startup, so restart the portal
  # once the fixture studies exist before exercising authenticated WSI access.
  # This keeps the validation faithful to the production cache contract while
  # making the dynamically imported restricted-study assertion deterministic.
  log "restarting portal to rebuild authorization cache after import"
  compose restart cbioportal >"$COMPOSE_LOG" 2>&1
  wait_http http://127.0.0.1:8080/api/health 180
}

start_frontend() {
  local tile_port="$1"
  stop_frontend
  log "starting integration frontend"
  (cd "$FRONTEND_DIR" && \
    NODE_ENV=development HOST=0.0.0.0 PORT="$FRONTEND_PORT" \
    CBIOPORTAL_URL="https://localhost:${FRONTEND_PORT}" \
    CBIOPORTAL_PROXY_TARGET=http://localhost:8080 \
    WSI_TILE_PROXY_TARGET="http://localhost:${tile_port}" \
    exec setsid pnpm exec rspack serve -c rspack.config.js >"$FRONTEND_LOG" 2>&1) &
  FRONTEND_PID=$!
  wait_http "https://127.0.0.1:${FRONTEND_PORT}/" 120 true
}

prepare_frontend() {
  log 'installing frontend dependencies'
  (cd "$FRONTEND_DIR" && pnpm install --frozen-lockfile)
}

run_api_tests() {
  local mode="$1"
  log "running ${mode} resource-data hierarchy/access/tile API contract"
  (cd "$ROOT_DIR/src/e2e/js" && \
    CBIOPORTAL_URL=http://localhost:8080 \
    CBIOPORTAL_FRONTEND_URL="https://localhost:${FRONTEND_PORT}" \
    WSI_FRONTEND_ALLOW_SELF_SIGNED_TLS=true \
    WSI_AUTH_SECRET="$AUTH_SECRET" \
    WSI_AUTH_AUDIENCE="$AUTH_AUDIENCE" \
    WSI_TILE_SERVER_URL="http://localhost:${WSI_TILE_SERVER_PORT}" \
    WSI_LOCAL_AUTH_BYPASS="$WSI_LOCAL_AUTH_BYPASS" \
    WSI_REQUIRE_AUTHENTICATED_SETUP="$WSI_REQUIRE_AUTHENTICATED_SETUP" \
    WSI_BASIC_LOGIN_PASSWORD=wsi-ci-password \
    yarn test -- test/WsiHierarchyController/WsiHierarchyController.spec.ts \
      --grep 'WsiHierarchyController' --reporter spec)
}

run_browser_tests() {
  local mode="$1"
  log "running ${mode} browser WSI contract"
  local browser_dir="$FRONTEND_DIR/end-to-end-test-playwright"
  local authenticated_e2e=false
  if [[ "$mode" == authenticated ]]; then
    authenticated_e2e=true
  fi
  local browser_tests=()
  # Browser contracts per frontend variant (file names checked at the pins).
  # The package branch carries the viewer and the Pathology Slides tab; the
  # patient child has no Playwright spec of its own (a known gap: its timeline
  # track, undated notice and link scoping are covered by Jest in the
  # frontend-children job), so its variant runs the package contracts plus the
  # foundation mock.  The annotations/agent branch changes
  # wsi-foundation-route.spec.ts, which every variant runs.
  local package_tests=(tests/wsi-foundation-route.spec.ts tests/wsi-viewer.spec.ts)
  local study_tests=(tests/pathology-study-clinical-data.spec.ts)
  local patient_tests=(tests/wsi-foundation-mocked.spec.ts)
  local molecular_tests=(tests/wsi-molecular-mocked.spec.ts)
  local annotations_agent_tests=(tests/wsi-annotation-agent.spec.ts)
  # Mocks the study and WSI APIs: the pinned backend has no study-slides endpoint.
  local study_slides_tests=(tests/wsi-study-slides-mocked.spec.ts)
  case "$WSI_VARIANT" in
    package)
      browser_tests=("${package_tests[@]}")
      ;;
    study)
      browser_tests=(tests/wsi-foundation-route.spec.ts "${study_tests[@]}")
      ;;
    patient)
      browser_tests=("${package_tests[@]}" "${patient_tests[@]}")
      ;;
    molecular)
      browser_tests=(tests/wsi-foundation-route.spec.ts "${molecular_tests[@]}")
      ;;
    annotations-agent)
      browser_tests=(tests/wsi-foundation-route.spec.ts "${annotations_agent_tests[@]}")
      ;;
    study-slides)
      browser_tests=(tests/wsi-foundation-route.spec.ts "${study_slides_tests[@]}")
      ;;
    integration)
      browser_tests=(
        "${package_tests[@]}"
        "${study_tests[@]}"
        "${patient_tests[@]}"
        "${molecular_tests[@]}"
        "${annotations_agent_tests[@]}"
        "${study_slides_tests[@]}"
      )
      ;;
    *)
      echo "Unknown WSI_VARIANT: $WSI_VARIANT" >&2
      exit 2
      ;;
  esac
  for browser_test in "${browser_tests[@]}"; do
    if [[ ! -f "$browser_dir/$browser_test" ]]; then
      echo "required WSI browser test is missing: $browser_test" >&2
      exit 1
    fi
  done
  # The full stack serves a dev build, whose error overlay covers the page
  # when the chunk-retry test fails the OpenSeadragon chunk on purpose, so
  # the Retry click can't land. The frontend-children jobs run that test
  # against a production build.
  (cd "$browser_dir" && \
    CBIOPORTAL_URL="https://localhost:${FRONTEND_PORT}" \
    CBIO_URL=http://localhost:8080 \
    LOCALDEV=0 \
    PW_IGNORE_HTTPS_ERRORS=1 \
    PW_SUITE=wsi \
    WSI_VIEWER_BASE_URL="https://localhost:${FRONTEND_PORT}" \
    WSI_AUTH_PORTAL_URL=http://localhost:8080 \
    WSI_AUTHENTICATED_E2E="$authenticated_e2e" \
    WSI_ALLOW_BASIC_FALLBACK=true \
    WSI_BASIC_LOGIN_USERNAME=wsi-ci-user \
    WSI_BASIC_LOGIN_PASSWORD=wsi-ci-password \
    WSI_PROXY_REHEARSAL=1 \
    PLAYWRIGHT_JSON_OUTPUT_NAME=test-results/report.json \
    pnpm exec playwright test --config=playwright.wsi.config.ts \
      "${browser_tests[@]}" \
      --grep-invert 'private MSK-IMPACT|retries a failed OpenSeadragon chunk' \
      --reporter=line,json
    python3 - <<'PY'
import json
from pathlib import Path

report = json.loads(Path('test-results/report.json').read_text())
stats = report.get('stats', {})
assert stats.get('expected', 0) > 0, stats
assert stats.get('skipped', 0) == 0, stats
assert stats.get('unexpected', 0) == 0, stats
print('required full-stack browser cases executed:', stats)
PY
  )
}

build_portal_image
build_tile_image
prepare_compose
prepare_frontend
(cd "$ROOT_DIR/src/e2e/js" && yarn install --frozen-lockfile)
(cd "$FRONTEND_DIR/end-to-end-test-playwright" && pnpm install --frozen-lockfile --ignore-workspace && pnpm exec playwright install --with-deps chromium)

for mode in unauthenticated authenticated; do
  if [[ "$mode" == authenticated ]]; then
    tile_port=8082
    portal_authenticate=saml_plus_basic
    local_bypass=false
    WSI_TILE_SERVER_PORT="$tile_port"
  else
    tile_port=8081
    portal_authenticate=false
    local_bypass=true
    WSI_TILE_SERVER_PORT="$tile_port"
  fi
  start_tile "$tile_port"
  start_compose "$mode" "$tile_port" "$portal_authenticate" "$local_bypass"
  import_fixture_and_check_lifecycle
  start_frontend "$tile_port"
  run_api_tests "$mode"
  run_browser_tests "$mode"
  stop_compose
done

log "full-stack WSI resource-data validation (${WSI_VARIANT}) passed in both authentication modes"
